### ISSUE TITLE
Redirect user to event detail page if the submitted form is valid

### ISSUE THREAD

**Issue by bigcliff3** [mailkimp/mgt656-spring-2015-project#23]
This redirect is accomplished using a "302" HTTP response. (See the documentation for the Express.js response redirect method)

**Comment by ilan21** [comment]
Why is this reopened? It was working

**Comment by bigcliff3** [comment]
Test not passing for some reason.

ilan21 notifications@github.com wrote:

Why is this reopened? It was working

**Comment by ilan21** [comment]
Possible that I didnt push properly
